### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by gig3m** [knownasilya/sword#5]
Strings being parsed into books are case sensitive.

```
genesis 1
```

returns

```
[{"start":{"book":1,"chapter":1}}]
```

where 

```
Genesis 1
```

returns 

```
[{"start":{"chapter":1}}]
```

**Comment by gig3m** [comment]
I'll PR this tonight when I get a chance if you don't get to it before me.

**Comment by knownasilya** [comment]
@gig3m it's a race!

**Comment by gig3m** [comment]
@knownasilya You'll fix this before I get my reply in, I'd wager.  ;)
