### ISSUE TITLE
Path error -  'MODULE_NOT_FOUND'

### ISSUE THREAD

**Issue by gig3m** [knownasilya/sword#7]
When included in a project, Sword missteps on the path to the maps directory.

```
{ [Error: Cannot find module '/xxx/maps/en'] code: 'MODULE_NOT_FOUND' }
```

where 'xxx' is the parent directory of the project.

Correct path would be

```
/xxx/node_modules/sword/maps/en
```

**Comment by knownasilya** [comment]
Should be fixed in 0.4.1, thanks!
