### ISSUE TITLE
Direction/Interoperability Question

### ISSUE THREAD

**Issue by gig3m** [knownasilya/sword#9]
@knownasilya,

First off, thanks for your awesome package, keep up the good work.

Do you have a place where you are heading with this project?  Is there a bigger project in mind or are you just wanting to create a parser?

I'm working on a CLI for exporting bible text in several versions, languages, and formats.  The main problem I was trying to solve is an export with no verse numbers, paragraph breaks, or subtitles.  Essentially pure text since this is the way I study (see Inductive Bible Study).  Formatting is simply a matter of preference and I figured I'd just make those all options.

I've been looking at formats for storing the actual text, from json and xml (osis) to a sqlite database.  It would be nice to create a common data format if other people are creating tools as well.

Anyways, if some or any of this somehow falls into the scope of a package you were working on or were planning, let me know.

Again, thanks for sword.

@gig3m

**Comment by knownasilya** [comment]
@gig3m thanks.

> Do you have a place where you are heading with this project? Is there a bigger project in mind or are you just wanting to create a parser?

I'm looking to consume this module in the context of a web application for presenting
sermons/bible passages in a bilingual setting. Where slides have references and the references
generate "slides" for the passages they reference.

> I'm working on a CLI for exporting bible text in several versions, languages, and formats.

That sounds very nice! Would love for that to be beyond just CLI, but also expose a programatic API (build it programatic API first and put CLI on top).

> I've been looking at formats for storing the actual text, from json and xml (osis) to a sqlite database. 

I've also looked at some of this, my current approach is storing it in a nosql db (RethinkDB in my case).

> It would be nice to create a common data format if other people are creating tools as well.

Totally agree!

Would love to learn more about what you're doing and to be involved!

**Comment by gig3m** [comment]
Responded via email.
